# theta가 정규분포가 아닌 경우에...

results.gpcm
theta<-score.GPCM
mark<-ifelse(theta<quantile(theta,probs = 0.025),0,1)
true<-cbind(theta,mark)
true<-as.data.frame(true)
colnames(true)<-c('theta','mark')
true_a<-filter(true,true$theta>quantile(true$theta,probs = 0.025)&true$mark==1)
true_b<-filter(true,theta>quantile(true$theta,probs = 0.025)&mark==0) 
true_c<-filter(true,theta<=quantile(true$theta,probs = 0.025)&mark==1) 
true_d<-filter(true,theta<=quantile(true$theta,probs = 0.025)&mark==0) 
nrow(true_a)
nrow(true_b)
nrow(true_c)
nrow(true_d)
true_FPR<-(nrow(true_c)/(nrow(true_a)+nrow(true_c)))
print(true_FPR)
true_FNR<-(nrow(true_b)/(nrow(true_b)+nrow(true_d))) 
print(true_FNR)
true_sens<-(nrow(true_d)/(nrow(true_b)+nrow(true_d)))
print(true_sens)
true_spec<-(nrow(true_a)/(nrow(true_a)+nrow(true_c)))
print(true_spec)
true_PPP<-(nrow(true_d)/(nrow(true_d)+nrow(true_c)))
print(true_PPP)
true_NPP<-(nrow(true_a)/(nrow(true_a)+nrow(true_b)))
print(true_NPP)
true_PCO<-((nrow(true_a)+nrow(true_d))/(nrow(true)))
print(true_PCO)
ROC(true$theta, true$mark)

########### 아... 중요한걸 놓쳤다.irt 점수에서 표준편차 몇점이 CTT에 대응하는지를 봐야하는데 봐야하는데
########### 단순히CTT에서표준편차 다시재면 아무의미없지~!~!


tscore<-expected.test(results.gpcm,as.matrix(theta))
swap1<-cbind(theta,tscore,mark)
swap1<-as.data.frame(swap1)
colnames(swap1)<-c('theta','tscore','mark')
print(swap1[swap1$theta<=-1.95,])
swap1_a<-filter(swap1,swap1$tscore>quantile(swap1$tscore,probs = 0.025)&swap1$mark==1)
swap1_b<-filter(swap1,tscore>quantile(swap1$tscore,probs = 0.025)&mark==0) 
swap1_c<-filter(swap1,tscore<=quantile(swap1$tscore,probs = 0.025)&mark==1) 
swap1_d<-filter(swap1,tscore<=quantile(swap1$tscore,probs = 0.025)&mark==0) 
nrow(swap1_a)
nrow(swap1_b)
nrow(swap1_c)
nrow(swap1_d)
swap1_FPR<-(nrow(swap1_c)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_FPR)
swap1_FNR<-(nrow(swap1_b)/(nrow(swap1_b)+nrow(swap1_d))) 
print(swap1_FNR)
swap1_sens<-(nrow(swap1_d)/(nrow(swap1_b)+nrow(swap1_d)))
print(swap1_sens)
swap1_spec<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_spec)
swap1_PPP<-(nrow(swap1_d)/(nrow(swap1_d)+nrow(swap1_c)))
print(swap1_PPP)
swap1_NPP<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_b)))
print(swap1_NPP)
swap1_PCO<-((nrow(swap1_a)+nrow(swap1_d))/(nrow(swap1)))
print(swap1_PCO)
ROC(swap1$tscore, swap1$mark)
rr
