#분위수로 해보깅 ㅎㅎ
# 진점수분포에서 2sd(백분위 2.5%?)지점을 CTT로 변환하면 어디인지 나올테지
# 이건 CTT의 표준편차를 보는거랑  다른 문제다 -> 정규분포가 아니므로 백분위를 봐야한다
# CTT에서의 컷오프 백분위가 진점수 백분위와 얼마가 차이가 나는가를 봐야한다..!
# 2.5%, 5%, 10%!
# 2.5% = -1.95 -> CTT 9.6점 c= 2.5%
# 5% = 
results.gpcm
theta<-rnorm(500,0,1)
quantile(theta,probs = 0.05)
mark<-ifelse(theta<quantile(theta,probs = 0.05),0,1)
true<-cbind(theta,mark)
true<-as.data.frame(true)
true_a<-filter(true,true$theta>quantile(true$theta,probs = 0.05)&true$mark==1)
true_b<-filter(true,theta>quantile(true$theta,probs = 0.05)&mark==0) 
true_c<-filter(true,theta<=quantile(true$theta,probs = 0.05)&mark==1) 
true_d<-filter(true,theta<=quantile(true$theta,probs = 0.05)&mark==0) 
nrow(true_a)
nrow(true_b)
nrow(true_c)
nrow(true_d)
true_FPR<-(nrow(true_c)/(nrow(true_a)+nrow(true_c)))
print(true_FPR)
true_FNR<-(nrow(true_b)/(nrow(true_b)+nrow(true_d))) 
print(true_FNR)
true_sens<-(nrow(true_d)/(nrow(true_b)+nrow(true_d)))
print(true_sens)
true_spec<-(nrow(true_a)/(nrow(true_a)+nrow(true_c)))
print(true_spec)
true_PPP<-(nrow(true_d)/(nrow(true_d)+nrow(true_c)))
print(true_PPP)
true_NPP<-(nrow(true_a)/(nrow(true_a)+nrow(true_b)))
print(true_NPP)
true_PCO<-((nrow(true_a)+nrow(true_d))/(nrow(true)))
print(true_PCO)
ROC(true$theta, true$mark)

########### 아... 중요한걸 놓쳤다.irt 점수에서 표준편차 몇점이 CTT에 대응하는지를 봐야하는데 봐야하는데
########### 단순히CTT에서표준편차 다시재면 아무의미없지~!~!


tscore<-expected.test(results.gpcm,as.matrix(theta))
swap1<-cbind(theta,tscore,mark)
swap1<-as.data.frame(swap1)
swap1_a<-filter(swap1,swap1$tscore>quantile(true$theta,probs = 0.05)&mark==1)
swap1_b<-filter(swap1,tscore>quantile(true$theta,probs = 0.05)&mark==0) 
swap1_c<-filter(swap1,tscore<=quantile(true$theta,probs = 0.05)&mark==1) 
swap1_d<-filter(swap1,tscore<=quantile(true$theta,probs = 0.05)&mark==0) 
nrow(swap1_a)
nrow(swap1_b)
nrow(swap1_c)
nrow(swap1_d)
swap1_FPR<-(nrow(swap1_c)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_FPR)
swap1_FNR<-(nrow(swap1_b)/(nrow(swap1_b)+nrow(swap1_d))) 
print(swap1_FNR)
swap1_sens<-(nrow(swap1_d)/(nrow(swap1_b)+nrow(swap1_d)))
print(swap1_sens)
swap1_spec<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_spec)
swap1_PPP<-(nrow(swap1_d)/(nrow(swap1_d)+nrow(swap1_c)))
print(swap1_PPP)
swap1_NPP<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_b)))
print(swap1_NPP)
swap1_PCO<-((nrow(swap1_a)+nrow(swap1_d))/(nrow(swap1)))
print(swap1_PCO)
ROC(swap1$tscore, swap1$mark)


tscore<-expected.test(results.gpcm,as.matrix(theta))
swap1<-cbind(theta,tscore,mark)
swap1<-as.data.frame(swap1)
print(swap1[swap1$theta<=-1.95,])
swap1_a<-filter(swap1,swap1$tscore>quantile(swap1$tscore,probs = 0.025)&swap1$mark==1)
swap1_b<-filter(swap1,tscore>quantile(swap1$tscore,probs = 0.025)&mark==0) 
swap1_c<-filter(swap1,tscore<=quantile(swap1$tscore,probs = 0.025)&mark==1) 
swap1_d<-filter(swap1,tscore<=quantile(swap1$tscore,probs = 0.025)&mark==0) 
nrow(swap1_a)
nrow(swap1_b)
nrow(swap1_c)
nrow(swap1_d)
swap1_FPR<-(nrow(swap1_c)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_FPR)
swap1_FNR<-(nrow(swap1_b)/(nrow(swap1_b)+nrow(swap1_d))) 
print(swap1_FNR)
swap1_sens<-(nrow(swap1_d)/(nrow(swap1_b)+nrow(swap1_d)))
print(swap1_sens)
swap1_spec<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_c)))
print(swap1_spec)
swap1_PPP<-(nrow(swap1_d)/(nrow(swap1_d)+nrow(swap1_c)))
print(swap1_PPP)
swap1_NPP<-(nrow(swap1_a)/(nrow(swap1_a)+nrow(swap1_b)))
print(swap1_NPP)
swap1_PCO<-((nrow(swap1_a)+nrow(swap1_d))/(nrow(swap1)))
print(swap1_PCO)
ROC(swap1$tscore, swap1$mark)


